/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import Controller.DaftarPeminjamanController;
import Model.Buku;
import Model.BukuDAO;
import Model.Export;
import Model.MahasiswaDAO;
import Model.Peminjaman;
import Model.PeminjamanDAO;
import java.io.File;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class DaftarPeminjaman extends javax.swing.JPanel {

     private DefaultTableModel tableModel;
    private DaftarPeminjamanController controller;
    
    public DaftarPeminjaman() throws SQLException {
        initComponents();
        tableModel = (DefaultTableModel) peminjamanTable.getModel();
        controller = new DaftarPeminjamanController(this);
    }
    
    public void updateTable(List<Peminjaman> listPeminjaman) {
        tableModel.setRowCount(0);

        for (Peminjaman peminjaman : listPeminjaman) {
            try {
                String nim = controller.getMahasiswaDAO().getNimByIdUser(peminjaman.getIdUser());
                Buku buku = controller.getBukuDAO().getBukuById(peminjaman.getIdBuku());
                String judulBuku = buku.getJudulBuku();
                int stok = buku.getStok();

                Object[] row = {
                    nim,
                    judulBuku,
                    stok,
                    peminjaman.getTglPinjam(),
                    peminjaman.getTglKembali(),
                    peminjaman.getStatusPinjam()
                };
                tableModel.addRow(row);
            } catch (SQLException ex) {
                Logger.getLogger(DaftarPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public javax.swing.JTextField getSearchTextField() {
        return searchTextField;
    }

    public javax.swing.JTextField getJudulTextField() {
        return judulTextField;
    }

    public javax.swing.JTextField getNimTextField() {
        return nimTextField;
    }

    public javax.swing.JTextField getStokTextField() {
        return stokTextField;
    }

    public javax.swing.JComboBox<String> getStatusComboBox() {
        return statusComboBox;
    }

    public com.toedter.calendar.JDateChooser getTglPinjamDateChooser() {
        return tglPinjamDateChooser;
    }

    public com.toedter.calendar.JDateChooser getTglKembaliDateChooser() {
        return tglKembaliDateChooser;
    }

    public javax.swing.JTable getPeminjamanTable() {
        return peminjamanTable;
    }

    public javax.swing.JFileChooser getExportFileChooser() {
        return exportFileChooser;
    }

    public void showDaftarPeminjamanPanel() {
        mainPanel.removeAll();
        mainPanel.add(daftarPeminjaman);
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    
    // Menampilkan panel updatePeminjaman
     public void showUpdatePeminjamanPanel() {
            mainPanel.removeAll();
            mainPanel.add(updatePeminjaman);
            mainPanel.repaint();
            mainPanel.revalidate();
     }
    




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exportFileChooser = new javax.swing.JFileChooser();
        mainPanel = new javax.swing.JPanel();
        daftarPeminjaman = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        exportButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        peminjamanTable = new javax.swing.JTable();
        updateButton = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        EditButton1 = new javax.swing.JButton();
        exportButton2 = new javax.swing.JButton();
        updatePeminjaman = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        nimTextField = new javax.swing.JTextField();
        judulTextField = new javax.swing.JTextField();
        stokTextField = new javax.swing.JTextField();
        simpanButton = new javax.swing.JButton();
        btn_batal4 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tglPinjamDateChooser = new com.toedter.calendar.JDateChooser();
        tglKembaliDateChooser = new com.toedter.calendar.JDateChooser();
        statusComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(51, 102, 255));
        setPreferredSize(new java.awt.Dimension(571, 486));
        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMinimumSize(new java.awt.Dimension(900, 860));
        mainPanel.setPreferredSize(new java.awt.Dimension(650, 580));
        mainPanel.setLayout(new java.awt.CardLayout());

        daftarPeminjaman.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel20.setText("Daftar Peminjaman");

        exportButton.setText("Export (.csv)");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        peminjamanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Judul Buku", "Stok", "Tanggal Pinjam", "Tanggal Kembali", "Status Pinjam"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(peminjamanTable);

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        searchTextField.setText("Ketik NIM untuk pencarian");
        searchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusLost(evt);
            }
        });

        EditButton1.setText("Reset");
        EditButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButton1ActionPerformed(evt);
            }
        });

        exportButton2.setText("Export (.pdf)");
        exportButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout daftarPeminjamanLayout = new javax.swing.GroupLayout(daftarPeminjaman);
        daftarPeminjaman.setLayout(daftarPeminjamanLayout);
        daftarPeminjamanLayout.setHorizontalGroup(
            daftarPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daftarPeminjamanLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(daftarPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(daftarPeminjamanLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(daftarPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(daftarPeminjamanLayout.createSequentialGroup()
                                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EditButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateButton))
                            .addGroup(daftarPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(daftarPeminjamanLayout.createSequentialGroup()
                                    .addComponent(exportButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(exportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        daftarPeminjamanLayout.setVerticalGroup(
            daftarPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daftarPeminjamanLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(daftarPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditButton1)
                    .addComponent(updateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(daftarPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportButton)
                    .addComponent(exportButton2))
                .addGap(0, 336, Short.MAX_VALUE))
        );

        mainPanel.add(daftarPeminjaman, "card2");

        updatePeminjaman.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel21.setText("Update Peminjaman");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Judul Buku");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Tanggal Kembali");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("NIM");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Stok");

        nimTextField.setEditable(false);

        judulTextField.setEditable(false);

        stokTextField.setEditable(false);

        simpanButton.setBackground(new java.awt.Color(204, 204, 255));
        simpanButton.setText("Simpan");
        simpanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        btn_batal4.setBackground(new java.awt.Color(204, 204, 255));
        btn_batal4.setText("Kembali");
        btn_batal4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_batal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal4ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Tanggal Pinjam");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setText("Status Pinjam");

        tglPinjamDateChooser.setBackground(new java.awt.Color(31, 43, 91,0));
        tglPinjamDateChooser.setForeground(new java.awt.Color(255, 255, 255));
        tglPinjamDateChooser.setToolTipText("");
        tglPinjamDateChooser.setEnabled(false);
        tglPinjamDateChooser.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        tglPinjamDateChooser.setOpaque(false);

        tglKembaliDateChooser.setBackground(new java.awt.Color(31, 43, 91,0));
        tglKembaliDateChooser.setForeground(new java.awt.Color(255, 255, 255));
        tglKembaliDateChooser.setToolTipText("");
        tglKembaliDateChooser.setEnabled(false);
        tglKembaliDateChooser.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        tglKembaliDateChooser.setOpaque(false);

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "diproses", "disetujui", "ditolak", "terlambat", "selesai" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_batal4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simpanButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel22)
                            .addComponent(jLabel25)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nimTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                            .addComponent(judulTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                            .addComponent(stokTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                            .addComponent(tglPinjamDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tglKembaliDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(judulTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stokTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tglPinjamDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel26)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglKembaliDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel23)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(70, 70, 70)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanButton)
                    .addComponent(btn_batal4))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout updatePeminjamanLayout = new javax.swing.GroupLayout(updatePeminjaman);
        updatePeminjaman.setLayout(updatePeminjamanLayout);
        updatePeminjamanLayout.setHorizontalGroup(
            updatePeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePeminjamanLayout.createSequentialGroup()
                .addGroup(updatePeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePeminjamanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(updatePeminjamanLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel21)))
                .addGap(56, 56, 56))
        );
        updatePeminjamanLayout.setVerticalGroup(
            updatePeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePeminjamanLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel21)
                .addGap(35, 35, 35)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 206, Short.MAX_VALUE))
        );

        mainPanel.add(updatePeminjaman, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
    controller.updateButtonAction();

    }//GEN-LAST:event_updateButtonActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        controller.simpanButtonAction();
    }//GEN-LAST:event_simpanButtonActionPerformed

    
    private void btn_batal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal4ActionPerformed
        controller.btnBatalAction();
    }//GEN-LAST:event_btn_batal4ActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        // TODO add your handling code here:
         controller.exportToCSV();
    }//GEN-LAST:event_exportButtonActionPerformed

    private void searchTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusGained
        // TODO add your handling code here:
        if (searchTextField.getText().equals("Ketik NIM untuk pencarian")) {
            searchTextField.setText("");
        }
    }//GEN-LAST:event_searchTextFieldFocusGained

    private void searchTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusLost
        // TODO add your handling code here:
        if (searchTextField.getText().isEmpty()) {
            
                    
            searchTextField.setText("Ketik NIM untuk pencarian");
        }
    }//GEN-LAST:event_searchTextFieldFocusLost

    private void EditButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButton1ActionPerformed
        // TODO add your handling code here:
         searchTextField.setText("Ketik NIM untuk Pencarian");
    }//GEN-LAST:event_EditButton1ActionPerformed

    private void exportButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButton2ActionPerformed
        // TODO add your handling code here:
       controller.exportToPDF();
    }//GEN-LAST:event_exportButton2ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditButton1;
    private javax.swing.JButton btn_batal4;
    private javax.swing.JPanel daftarPeminjaman;
    private javax.swing.JButton exportButton;
    private javax.swing.JButton exportButton2;
    private javax.swing.JFileChooser exportFileChooser;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField judulTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JTable peminjamanTable;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton simpanButton;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JTextField stokTextField;
    private com.toedter.calendar.JDateChooser tglKembaliDateChooser;
    private com.toedter.calendar.JDateChooser tglPinjamDateChooser;
    private javax.swing.JButton updateButton;
    private javax.swing.JPanel updatePeminjaman;
    // End of variables declaration//GEN-END:variables
}


