/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import Controller.DaftarAnggotaController;
import Model.Export;
import Model.Mahasiswa;
import Model.MahasiswaDAO;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;



public class DaftarAnggota extends javax.swing.JPanel {

    private DefaultTableModel tableModel;
    private DaftarAnggotaController mahasiswaController;
    
    public DaftarAnggota() throws SQLException {
        initComponents();
        tableModel = (DefaultTableModel) anggotaTable.getModel();
        mahasiswaController = new DaftarAnggotaController(this);
        mahasiswaController.loadTableData(); // Memuat data buku ke dalam tabel saat panel ini diinisialisasi
        addDocumentListenerToSearchField(); // Menambahkan DocumentListener ke searchTextField
    }

    
    public String getSearchQuery() {
        return searchTextField.getText().trim();
    }

    public String getNim() {
        return nimTextField.getText();
    }

    public String getNama() {
        return namaTextField.getText();
    }

    public String getJk() {
        return (String) jkComboBox.getSelectedItem();
    }

    public String getKelas() {
        return kelasTextField.getText();
    }

    public void resetForm() {
        nimTextField.setText("");
        namaTextField.setText("");
        jkComboBox.setSelectedIndex(0); // Pilih indeks pertama sebagai nilai default
        kelasTextField.setText("");
    }
    
    // Add these getter methods in DaftarAnggota.java
    public javax.swing.JPanel getMainPanel() {
        return mainPanel;
    }

    public javax.swing.JPanel getDaftarAnggota() {
        return daftarAnggota;
    }

    public javax.swing.JTable getAnggotaTable() {
        return anggotaTable;
    }

    
     public void updateTable(List<Mahasiswa> listMahasiswa) {
        tableModel.setRowCount(0); // Mengosongkan tabel sebelum dimuat ulang
        for (Mahasiswa mahasiswa : listMahasiswa) {
            Object[] row = {
                mahasiswa.getNim(),
                mahasiswa.getNama(),
                mahasiswa.getJk(),
                mahasiswa.getKelas()
            };
            tableModel.addRow(row);
        }
    }
     
    private void addDocumentListenerToSearchField() {
        searchTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                mahasiswaController.searchMahasiswa();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                mahasiswaController.searchMahasiswa();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                mahasiswaController.searchMahasiswa();
            }
        });
    }

    
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exportFileChooser = new javax.swing.JFileChooser();
        mainPanel = new javax.swing.JPanel();
        daftarAnggota = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        anggotaTable = new javax.swing.JTable();
        TambahAnggotaButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        EditButton1 = new javax.swing.JButton();
        tambahAnggota = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        nimTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        kelasTextField = new javax.swing.JTextField();
        simpanButton = new javax.swing.JButton();
        btn_batal4 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        jkComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(51, 102, 255));
        setPreferredSize(new java.awt.Dimension(571, 486));
        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMinimumSize(new java.awt.Dimension(900, 860));
        mainPanel.setPreferredSize(new java.awt.Dimension(650, 580));
        mainPanel.setLayout(new java.awt.CardLayout());

        daftarAnggota.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel20.setText("Daftar Anggota");

        anggotaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Jenis Kelamin", "Kelas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(anggotaTable);

        TambahAnggotaButton.setText("Tambah Anggota");
        TambahAnggotaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahAnggotaButtonActionPerformed(evt);
            }
        });

        exportButton.setText("Export (.csv)");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        searchTextField.setText("Ketik NIM untuk pencarian");
        searchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusLost(evt);
            }
        });

        EditButton1.setText("Reset");
        EditButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout daftarAnggotaLayout = new javax.swing.GroupLayout(daftarAnggota);
        daftarAnggota.setLayout(daftarAnggotaLayout);
        daftarAnggotaLayout.setHorizontalGroup(
            daftarAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daftarAnggotaLayout.createSequentialGroup()
                .addGroup(daftarAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(daftarAnggotaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel20))
                    .addGroup(daftarAnggotaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(daftarAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(daftarAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(daftarAnggotaLayout.createSequentialGroup()
                                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(EditButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TambahAnggotaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        daftarAnggotaLayout.setVerticalGroup(
            daftarAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daftarAnggotaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(daftarAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TambahAnggotaButton)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exportButton)
                .addGap(0, 326, Short.MAX_VALUE))
        );

        mainPanel.add(daftarAnggota, "card2");

        tambahAnggota.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel21.setText("Tambah Anggota");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Nama :");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("NIM");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Jenis Kelamin");

        simpanButton.setBackground(new java.awt.Color(204, 204, 255));
        simpanButton.setText("Simpan");
        simpanButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        btn_batal4.setBackground(new java.awt.Color(204, 204, 255));
        btn_batal4.setText("Kembali");
        btn_batal4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_batal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal4ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Kelas");

        resetButton.setBackground(new java.awt.Color(204, 204, 255));
        resetButton.setText("Reset");
        resetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jkComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_batal4)
                        .addGap(34, 34, 34)
                        .addComponent(resetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simpanButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel22)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nimTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                            .addComponent(namaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                            .addComponent(kelasTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                            .addComponent(jkComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel25))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton)
                    .addComponent(btn_batal4)
                    .addComponent(simpanButton))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahAnggotaLayout = new javax.swing.GroupLayout(tambahAnggota);
        tambahAnggota.setLayout(tambahAnggotaLayout);
        tambahAnggotaLayout.setHorizontalGroup(
            tambahAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahAnggotaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(tambahAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahAnggotaLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 589, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tambahAnggotaLayout.setVerticalGroup(
            tambahAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahAnggotaLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel21)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        mainPanel.add(tambahAnggota, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void TambahAnggotaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahAnggotaButtonActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(tambahAnggota);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_TambahAnggotaButtonActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
       mahasiswaController.saveMahasiswa();
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void btn_batal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal4ActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.add(daftarAnggota);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_batal4ActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_resetButtonActionPerformed
    
    
    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        // TODO add your handling code here:
        mahasiswaController.exportToCSV();

    }//GEN-LAST:event_exportButtonActionPerformed

    private void searchTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusGained
        // TODO add your handling code here:
        if (searchTextField.getText().equals("Ketik NIM untuk pencarian")) {
            searchTextField.setText("");
        }
    }//GEN-LAST:event_searchTextFieldFocusGained

    private void searchTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusLost
        // TODO add your handling code here:
        if (searchTextField.getText().isEmpty()) {
            searchTextField.setText("Ketik NIM untuk pencarian");
        }
    }//GEN-LAST:event_searchTextFieldFocusLost

    private void EditButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButton1ActionPerformed
        // TODO add your handling code here
         searchTextField.setText("Ketik NIM untuk pencarian");
    }//GEN-LAST:event_EditButton1ActionPerformed

    private void exportPdfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportPdfButtonActionPerformed
        // TODO add your handling code here:
         mahasiswaController.exportToPDF();
    }//GEN-LAST:event_exportPdfButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditButton1;
    private javax.swing.JButton TambahAnggotaButton;
    private javax.swing.JTable anggotaTable;
    private javax.swing.JButton btn_batal4;
    private javax.swing.JPanel daftarAnggota;
    private javax.swing.JButton exportButton;
    private javax.swing.JFileChooser exportFileChooser;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jkComboBox;
    private javax.swing.JTextField kelasTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton simpanButton;
    private javax.swing.JPanel tambahAnggota;
    // End of variables declaration//GEN-END:variables


}

