/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import Model.Mahasiswa;
import Model.MahasiswaDAO;
import Model.SessionManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static Controller.HashUtil.hashPassword;

/**
 *
 * @author hp
 */
public class Profil extends javax.swing.JPanel {

    /**
     * Creates new form Form_Barang
     */
    
    public Profil() {
        
        initComponents();
        loadData();
    }
    
    private void loadData() {
        String nim = SessionManager.getInstance().getNim();
        if (nim != null) {
            try {
                MahasiswaDAO mahasiswaDAO = new MahasiswaDAO();
                Mahasiswa mahasiswa = mahasiswaDAO.getMahasiswaByNim(nim);

                if (mahasiswa != null) {
                    nimTextField.setText(mahasiswa.getNim());
                    namaTextField.setText(mahasiswa.getNama());
                    jkTextField.setText(mahasiswa.getJk());
                    kelasTextField.setText(mahasiswa.getKelas());
                } else {
                    JOptionPane.showMessageDialog(this, "Data mahasiswa tidak ditemukan!");
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Gagal memuat data mahasiswa: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "NIM tidak ditemukan dalam sesi!");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        profil = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        kelasTextField = new javax.swing.JLabel();
        btn_simpan5 = new javax.swing.JButton();
        jkTextField = new javax.swing.JLabel();
        nimTextField = new javax.swing.JLabel();
        namaTextField = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        resetPassword = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        nimUserTextField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        resetPasswordButton = new javax.swing.JButton();
        baruPasswordField = new javax.swing.JPasswordField();
        baru2PasswordField = new javax.swing.JPasswordField();
        lamaPasswordField = new javax.swing.JPasswordField();
        batalkanReset = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 102, 255));
        setPreferredSize(new java.awt.Dimension(571, 486));
        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMinimumSize(new java.awt.Dimension(900, 860));
        mainPanel.setPreferredSize(new java.awt.Dimension(650, 580));
        mainPanel.setLayout(new java.awt.CardLayout());

        profil.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel20.setText("Profil Pengguna");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Nama");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("NIM");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Jenis Kelamin");

        kelasTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btn_simpan5.setBackground(new java.awt.Color(204, 204, 255));
        btn_simpan5.setText("Reset Password");
        btn_simpan5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_simpan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan5ActionPerformed(evt);
            }
        });

        jkTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        nimTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        namaTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setText("Kelas");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_simpan5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel21)
                            .addComponent(jLabel24)
                            .addComponent(jLabel33))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jkTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                            .addComponent(kelasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(312, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(nimTextField))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(namaTextField))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jkTextField))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelasTextField)
                    .addComponent(jLabel33))
                .addGap(64, 64, 64)
                .addComponent(btn_simpan5)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout profilLayout = new javax.swing.GroupLayout(profil);
        profil.setLayout(profilLayout);
        profilLayout.setHorizontalGroup(
            profilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(profilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(profilLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        profilLayout.setVerticalGroup(
            profilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel20)
                .addGap(32, 32, 32)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPanel.add(profil, "card2");

        resetPassword.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel22.setText("Reset Password");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Password lama");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setText("NIM");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setText("Password baru");

        nimUserTextField.setEditable(false);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("Konfirmasi password baru");

        resetPasswordButton.setBackground(new java.awt.Color(204, 204, 255));
        resetPasswordButton.setText("Reset Password");
        resetPasswordButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPasswordButtonActionPerformed(evt);
            }
        });

        batalkanReset.setBackground(new java.awt.Color(204, 204, 255));
        batalkanReset.setText("Batalkan");
        batalkanReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        batalkanReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalkanResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel27))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nimUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(baruPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(baru2PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lamaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(batalkanReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetPasswordButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(nimUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(lamaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(baruPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(baru2PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetPasswordButton)
                    .addComponent(batalkanReset))
                .addContainerGap(219, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout resetPasswordLayout = new javax.swing.GroupLayout(resetPassword);
        resetPassword.setLayout(resetPasswordLayout);
        resetPasswordLayout.setHorizontalGroup(
            resetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPasswordLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(resetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(resetPasswordLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        resetPasswordLayout.setVerticalGroup(
            resetPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPasswordLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel22)
                .addGap(32, 32, 32)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPanel.add(resetPassword, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpan5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan5ActionPerformed
        // TODO add your handling code here:
        String nim = SessionManager.getInstance().getNim();
        nimUserTextField.setText(nim);
        mainPanel.removeAll();
        mainPanel.add(resetPassword);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btn_simpan5ActionPerformed

    private void resetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPasswordButtonActionPerformed
        try {
            // Mendapatkan NIM dari session manager
            String nim = SessionManager.getInstance().getNim();
            
            // Mendapatkan ID pengguna dari mahasiswaDAO
            MahasiswaDAO mahasiswaDAO = new MahasiswaDAO();
            int idUser = mahasiswaDAO.getIdUserByNim(nim);
            
            // Mendapatkan password lama dari JPasswordField
            char[] lamaPasswordChars = lamaPasswordField.getPassword();
            String lamaPassword = new String(lamaPasswordChars);
            
            
            if (mahasiswaDAO.authenticate(nim, lamaPassword)) {
                // Password lama cocok, lanjutkan dengan verifikasi password baru
                char[] baruPasswordChars = baruPasswordField.getPassword();
                char[] baru2PasswordChars = baru2PasswordField.getPassword();
                String baruPassword = new String(baruPasswordChars);
                String baru2Password = new String(baru2PasswordChars);
                
                // Verifikasi kedua password baru harus sesuai
                if (baruPassword.equals(baru2Password)) {
                    // Lakukan hashing password baru sebelum menyimpan ke database
                    String hashedPassword = hashPassword(baruPassword);
                    
                    // Melakukan update password menggunakan UserModel
                    boolean updateSuccess = mahasiswaDAO.updatePassword(idUser, hashedPassword);
                    
                    if (updateSuccess) {
                        JOptionPane.showMessageDialog(null, "Password berhasil direset!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                        // Reset kolom password setelah berhasil
                        lamaPasswordField.setText("");
                        baruPasswordField.setText("");
                        baru2PasswordField.setText("");
                        
                        //profil
                        mainPanel.removeAll();
                        mainPanel.add(profil);
                        mainPanel.repaint();
                        mainPanel.revalidate();
                    } else {
                        JOptionPane.showMessageDialog(null, "Gagal mereset password.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Password baru tidak cocok.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Password lama salah.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Profil.class.getName()).log(Level.SEVERE, null, ex);
        }

    
    }//GEN-LAST:event_resetPasswordButtonActionPerformed

    private void batalkanResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalkanResetActionPerformed
        // TODO add your handling code here:
         lamaPasswordField.setText("");
         baruPasswordField.setText("");
         baru2PasswordField.setText("");
         nimUserTextField.setText("");

        mainPanel.removeAll();
        mainPanel.add(profil);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_batalkanResetActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField baru2PasswordField;
    private javax.swing.JPasswordField baruPasswordField;
    private javax.swing.JButton batalkanReset;
    private javax.swing.JButton btn_simpan5;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jkTextField;
    private javax.swing.JLabel kelasTextField;
    private javax.swing.JPasswordField lamaPasswordField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaTextField;
    private javax.swing.JLabel nimTextField;
    private javax.swing.JTextField nimUserTextField;
    private javax.swing.JPanel profil;
    private javax.swing.JPanel resetPassword;
    private javax.swing.JButton resetPasswordButton;
    // End of variables declaration//GEN-END:variables
}

